### ISSUE TITLE
Use monospace font for urls

### ISSUE THREAD

**Issue by Crystal-RainSlide** [einaregilsson/Redirector#169]
This will increase visual for heavy users.

Add `url` to the class name of patterns and the Example, and this style rule will work fine:
``` CSS
.redirect-info div p.url,
#edit-redirect-form input {
	font-family: monospace;
}
```
