### ISSUE TITLE
Making disabled state more obvious

### ISSUE THREAD

**Issue by Gitoffthelawn** [einaregilsson/Redirector#50]
When Redirector is disabled, it is not always obvious.  I added this CSS code.  It might interest you... or might not. :-)

``` CSS
/* Redirector extension button in menu panel: make disabled state much more prominent */

#toggle-button--redirectoreinaregilssoncom-redirector[image=
   "resource://redirector-at-einaregilsson-dot-com/images/icon-disabled-32.png"] {
      background-color: red !important; }

#toggle-button--redirectoreinaregilssoncom-redirector[image=
   "resource://redirector-at-einaregilsson-dot-com/images/icon-disabled-32.png"] > .toolbarbutton-multiline-text::after {
      content: " (Disabled) "; }
```
